NCI-C4CP/studyManagerDashboard

- src/utils.js
Required to make the button display in dev for [1084](https://github.com/episphere/connect/issues/1084).
> Added dev URL to list of URLs

- src/storeNotifications.js
Fix bug in [PR#14](https://github.com/episphere/studyManagerDashboard/pull/14)
> Handle empty string

- src/participantSummaryRow.js
As requested in follow-up comment on [1073](https://github.com/episphere/connect/issues/1073).
> Timeline message for 2024 Connect Experience survey changed

- src/participantSummaryRow.js
For Issue: https://github.com/episphere/connect/issues/1124
> Update the Survey Status for Expreience Survey

- newsletter/fallnewsletter-2024-spanish.html
- newsletter/fallnewsletter-2024.html
Ref: https://github.com/episphere/connect/issues/1072
> #1072: Fallnewsletter 2024

- newsletter/fallnewsletter-2024.html
Ref: https://github.com/episphere/connect/issues/1072
English links: https://github.com/episphere/connect/issues/1072#issuecomment-2430950005
Spanish links: https://github.com/episphere/connect/issues/1072#issuecomment-2432242473
> [#1072] Fix: hyperlink

- newsletter/fallnewsletter-2024-spanish.html
Ref: https://github.com/episphere/connect/issues/1072
> [#1072] Update the spanish url

- serviceWorker.js
> Service Worker Version Update

- src/fieldToConceptIdMapping.js
- src/participantDetails.js
- src/participantDetailsHelpers.js
Related: https://github.com/episphere/connect/issues/1186
•Refine alt address handling.
•Handle 646504105.
•Remove old code (initial alt contact code is old and was never implemented).
> alt contact and alt address refinements

- serviceWorker.js
- src/participantDetailsHelpers.js
Related: https://github.com/episphere/connect/issues/1186
•Include Alt POBox in UP History
•Update appVersion
> alt PO Box to UP History, update appVersion

- src/dataCorrectionsTool/incentiveEligibilityTool.js
- src/dataCorrectionsTool/verificationCorrectionsTool.js
- src/fieldToConceptIdMapping.js
- src/idsToName.js
- src/utils.js
For Issues: https://github.com/episphere/connect/issues/1218 and https://github.com/episphere/connect/issues/1210
> Updates for Verification Date and new Duplicate Type

- index.js
- src/fieldToConceptIdMapping.js
- src/navigationBar.js
- src/replaceHomeCollectionKit.js
Adds UI for requesting replacement home MW kits ([1142](https://github.com/episphere/connect/issues/1142))
> Now has a functioning UI to request replacement home MW kits (1142)

- src/dataCorrectionsTool/verificationCorrectionsTool.js
- src/participantCommons.js
- src/utils.js
Fixes for Issues found in Testing.  For Issues: https://github.com/episphere/connect/issues/1210
and https://github.com/episphere/connect/issues/1218
> Updates for the Verification Tool

- newsletter/2025/spring.html
- serviceWorker.js
https://github.com/episphere/connect/issues/1189
> [#1189] En spring newsletter

- newsletter/2025/spring-spanish.html
Ref: https://www.cancer.gov/connect-prevention-study/espanol/noticias/muestras_biológicas
> Add the Spanish spring newsletter

- newsletter/2025/spring.html
https://github.com/episphere/connect/issues/1189
> Update CSS for the spring newsletter english ver

- newsletter/2025/spring-spanish.html
Ref: https://github.com/episphere/connect/issues/1189#issuecomment-2773498278
> Update the spring newsletter (Spanish)

- newsletter/2025/spring-spanish.html
Ref: https://github.com/episphere/connect/issues/1189
> [#1189] Update CSS

- index.js
- serviceWorker.js
- src/fieldToConceptIdMapping.js
- src/idsToName.js
- src/participantCommons.js
- src/participantDetailsHelpers.js
- src/participantSummaryRow.js
- src/utils.js
Related:
Reinvitation Bubbles: https://github.com/episphere/connect/issues/1266
Remove external JSON dependency & Table handling refactoring/cleanup: https://github.com/episphere/connect/issues/1284
• Add reinvitation bubbles.
• Remove external JSON dependency.
• Refactor search table handling.
> 1266 add reinvitation bubbles

- src/participantSummaryRow.js
- src/replaceHomeCollectionKit.js
Participant summary row changes for [1289](https://github.com/episphere/connect/issues/1289);
Fixed an issue with the request replacement button showing when participant is ineligible
> 1289 implementation

- src/participantCommons.js
This PR addresses the following Issue:
* https://github.com/episphere/connect/issues/1278
-----
* Updated logic for determining when to disabled `Next` button
* Removed data length check in rendering conditionality
> Offset Pagination - Bug Fixes

- src/participantSummaryRow.js
Follow-up for [1289](https://github.com/episphere/connect/issues/1289) feedback,
> Fixed date which displays for home MW kits on participant summary

- index.html
- index.js
- src/dataCorrectionsTool/verificationCorrectionsTool.js
- src/participantChartsRender.js
- src/participantCommons.js
- src/participantLookup.js
- src/participantWithdrawalForm.js
- src/retrieveNotifications.js
- src/storeNotifications.js
- src/utils.js
This PR addresses the following Issue:
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/6
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/14
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/13
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/8
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/7
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/3
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/2
* https://github.com/NCI-C4CP/studyManagerDashboard/security/code-scanning/1
-----
* Implemented `escapeHTML()` and utilized across multiple forms to address cross-site scripting vulnerabilities
* Added integrity checks …
> Security Scan Fixes

- src/participantDetailsHelpers.js
update empty string originally to null in UP History(569151507). when adding Physical/Alt address via SMDB
https://github.com/episphere/connect/issues/1317
> update value in history

- serviceWorker.js
- src/fieldToConceptIdMapping.js
- src/participantSummary.js
- src/participantSummaryRow.js
DHQ MVP implementation - SMDB
Related: https://github.com/episphere/connect/issues/1238
• Add DHQ to the participant summary page.
> Add dhq survey to SMDB participant summary

- src/fieldToConceptIdMapping.js
- src/idsToName.js
For Issue: https://github.com/episphere/connect/issues/1236
This adds the Sanford Health Reported Ethnicity to the bubble fields.  It also adds all the constants for the values.  All the labels came from the data dictionary
> Added Sanford Health Ethnicity to the Bubble Fields

- src/participantDetailsHelpers.js
https://github.com/episphere/connect/issues/1317
> temp revert

- src/idsToName.js
- src/participantCommons.js
- src/participantDetails.js
This PR addresses the following Issue:
* https://github.com/episphere/connect/issues/1331
-----
* Updated text mapping for Account Phone and Account Email
* Removed unnecessary parameter
* Disabled rows and hid values for Account Phone and Account email if participant hasn't consented yet
> SMDB Firebase Login Hiding

- serviceWorker.js
- src/fieldToConceptIdMapping.js
- src/participantSummary.js
- src/participantSummaryRow.js
DHQ Phase 2 - HEI reports
Related: https://github.com/episphere/connect/issues/1327
•Integrate DHQ HEI Reports with the participant summary page.
•Draw the report generated date on the report PDF (survey submission date) and download it.
> DHQ Phase 2 - HEI reports

- .gitignore
- assets/css/dashboard.css
- index.js
- src/navigationBar.js
- src/pathologyReportUpload.js
- src/storeNotifications.js
This PR implements requirements described in issue [#1244](https://github.com/episphere/connect/issues/1244).  Below are details: 
- Permission setups based on requirements
- Drag or select files for upload
- Check file names
- Check duplicate files after selection and before uploading
- Displayed all uploaded fine names
- Cleanups for notification specs editing
> Upload pathology reports to SMDB

- src/navigationBar.js
This PR fixes [PR#117](https://github.com/NCI-C4CP/studyManagerDashboard/pull/117), to disallow only NORC for file uploading.
> Fix permission for pahology report upload

- index.js
- serviceWorker.js
- src/ehrUpload.js
- src/navigationBar.js
- src/pathologyReportUpload.js
This PR implement EHR uploads in SMDB frontend, as described in [issue#1373](https://github.com/episphere/connect/issues/1373).
Known issue: unable to handle large files (50MB to multiple GB)
Todo: Needs decisions on signed upload URLs
> Upload EHR

- assets/css/dashboard.css
- index.js
- src/idsToName.js
- src/navigationBar.js
- src/participantCommons.js
- src/participantDetails.js
- src/participantDetailsHelpers.js
- src/participantLookup.js
- src/participantSummary.js
- src/siteMessages.js
- src/utils.js
Refactors navigation handling, participant form validation, table rendering, and beginnings of state management implementation.
Related:
https://github.com/episphere/connect/issues/1276
https://github.com/episphere/connect/issues/1281
https://github.com/episphere/connect/issues/1282
https://github.com/episphere/connect/issues/1387
https://github.com/episphere/connect/issues/1411
https://github.com/episphere/connect/issues/1435
> navigation, profile editing, validation, table handling, etc.
